/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIclient;

/**
 *
 * @author Fahmee
 */
import BusinessClasses.EmployeeList;
import BusinessClasses.Employee;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
import java.util.HashMap;

public class EmployeeManagemenetForm extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeManagemenetForm
     */
    public static EmployeeList objemployeeList = new EmployeeList();
    public EmployeeManagemenetForm() {
        initComponents();
        this.getContentPane().setBackground(Color.yellow);
        try {
                //Load the collection with data from File   
                objemployeeList.load();
                
                //Disables the X Close button on the Frame.
                //Done so user MUST click the Exit button to exit frame
                setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

                   }
        catch (Exception objE) {
            //Trapping for any errors 
            JOptionPane.showMessageDialog(null, objE.toString());
        }       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ssLbl = new javax.swing.JLabel();
        fnLbl = new javax.swing.JLabel();
        lnLbl = new javax.swing.JLabel();
        dobLbl = new javax.swing.JLabel();
        addLbl = new javax.swing.JLabel();
        phLbl = new javax.swing.JLabel();
        txtSS = new javax.swing.JTextField();
        txtFN = new javax.swing.JTextField();
        txtLN = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txtADDRESS = new javax.swing.JTextField();
        txtPHONE = new javax.swing.JTextField();
        ageLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        jobLbl = new javax.swing.JLabel();
        txtAGE = new javax.swing.JTextField();
        txtEMAIL = new javax.swing.JTextField();
        txtJOB = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        printBtn = new javax.swing.JButton();
        printallBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmployeeList1 = new javax.swing.JList();
        listBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("EMPLOYEE MANAGEMENT");

        ssLbl.setText("Social Security number");

        fnLbl.setText("First Name");

        lnLbl.setText("Last Name");

        dobLbl.setText("Date of Birth");

        addLbl.setText("Address");

        phLbl.setText("Phone");

        txtFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNActionPerformed(evt);
            }
        });

        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });

        txtADDRESS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtADDRESSActionPerformed(evt);
            }
        });

        txtPHONE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPHONEActionPerformed(evt);
            }
        });

        ageLbl.setText("Age");

        emailLbl.setText("Email");

        jobLbl.setText("Job Title");

        txtJOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJOBActionPerformed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        removeBtn.setText("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        printBtn.setText("Print");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });

        printallBtn.setText("Print All");
        printallBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printallBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("EXIT");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(EmployeeList1);

        listBtn.setText("List");
        listBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPHONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAGE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addBtn)
                                    .addComponent(searchBtn)
                                    .addComponent(editBtn)
                                    .addComponent(removeBtn)
                                    .addComponent(printBtn)
                                    .addComponent(printallBtn)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                                .addComponent(listBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ssLbl)
                                    .addComponent(fnLbl)
                                    .addComponent(lnLbl)
                                    .addComponent(dobLbl)
                                    .addComponent(addLbl)
                                    .addComponent(phLbl)
                                    .addComponent(ageLbl)
                                    .addComponent(emailLbl)
                                    .addComponent(jobLbl))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtADDRESS, txtAGE, txtDOB, txtEMAIL, txtFN, txtJOB, txtLN, txtPHONE, txtSS});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addBtn, editBtn, jButton1, printBtn, printallBtn, removeBtn, searchBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ssLbl)
                            .addComponent(txtSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBtn))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fnLbl)
                            .addComponent(txtFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBtn))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lnLbl)
                            .addComponent(txtLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editBtn))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dobLbl)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeBtn))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addLbl)
                            .addComponent(txtADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(printBtn))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phLbl)
                            .addComponent(txtPHONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(printallBtn))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ageLbl)
                            .addComponent(txtAGE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLbl))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jobLbl)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(listBtn)
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(exitBtn)
                        .addGap(22, 22, 22))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtADDRESS, txtAGE, txtDOB, txtEMAIL, txtFN, txtJOB, txtLN, txtPHONE, txtSS});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addBtn, editBtn, jButton1, printBtn, printallBtn, removeBtn, searchBtn});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNActionPerformed

    private void txtPHONEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPHONEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPHONEActionPerformed

    private void txtJOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJOBActionPerformed

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed

    private void txtADDRESSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtADDRESSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtADDRESSActionPerformed

    private void listBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listBtnActionPerformed
        // TODO add your handling code here:
         try {
            //Create HashMap Pointer to hold HashMap List 
            //returned from Custom Collection Class Object
            HashMap<String, Employee> employeeList;
            
            
            //Get a POINTER to the internal HashMap Collection inside the Custom Collection
            //Class object
            employeeList = objemployeeList.getEmployeeList();

            //Clear the List
            EmployeeList1.removeAll();
            
            //To modify the elements in the list, you need to create a list model
            //Object (need to import the DefaultListModel Class)
            DefaultListModel<String> model = new DefaultListModel();
                   
            //Loop throught the HashMap collection using For Each Loop       
            for(Employee objCustomer : employeeList.values())
               {
                   //Read next Object & create comma-delimited string from the properties
                    String item = 
                    objCustomer.getSSNumber() + ","  + 
                    objCustomer.getFirstName()  + ","  + 
                    objCustomer.getLastName() + ","  +                                 
                    objCustomer.getDateOfBirth()  + ","  +
                    objCustomer.getAddress()  + ","  + 
                    objCustomer.getPhone()  + ","  +
                    objCustomer.getEmail()  + ","  +
                    objCustomer.getAge()  + ","  +
                            
                    objCustomer.getJobTitle();
                    
                    //Add item (comma-delimited line) to model
                    model.addElement(item);
                    
                    //Repeate process until all objects have been added
               }                             
   
            //SET the model to replace all items in the LIST
             EmployeeList1.setModel(model);
                       
            }
            catch (Exception objE) {
                //Trapping for any errors 
                JOptionPane.showMessageDialog(null,objE.toString());       
        }  
    }//GEN-LAST:event_listBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
         try {

            //Create a Customer pointer to store result of search
            Employee objemp;

            //Call the Search() method to do the work
            //TO Search for customer in list
            objemp = objemployeeList.search(txtSS.getText());

            //process results from method call
            //Customer found, display data
            if (objemp != null) {
                txtSS.setText(objemp.getSSNumber());
                txtFN.setText(objemp.getFirstName());
                txtLN.setText(objemp.getLastName());
                                
                txtDOB.setText(objemp.getDateOfBirth());
                txtADDRESS.setText(objemp.getAddress());
                txtPHONE.setText(objemp.getPhone());
                txtEMAIL.setText(objemp.getEmail());
                txtJOB.setText(objemp.getJobTitle());
                 txtAGE.setText(objemp.getAge().toString());
               
                
            } else {
                //Display msg that customer was not found
                JOptionPane.showMessageDialog(null, "Employee not found!");
            }        
        
        
        }
        catch (Exception objE) {
            //Trapping for any errors 
            JOptionPane.showMessageDialog(null, objE.toString());            
        }       
        
    }//GEN-LAST:event_searchBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        try {

            //Save & clear the collection when Frame is closing
            objemployeeList.save();
            objemployeeList.clear();
                   }
        catch (Exception objE) {
            //Trapping for any errors 
            JOptionPane.showMessageDialog(null, objE.toString());
        }                      
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        try {

            boolean success;


            //Create customer object to add
            Employee objNewCustomer = new Employee();

            //Set Object properties with data from TextField Controls
            objNewCustomer.setSSNumber(txtSS.getText());
            objNewCustomer.setFirstName(txtFN.getText());
            objNewCustomer.setLastName(txtLN.getText());                       
            objNewCustomer.setDateOfBirth(txtDOB.getText());
            objNewCustomer.setAddress(txtADDRESS.getText());
            objNewCustomer.setPhone(txtPHONE.getText());
            objNewCustomer.setEmail(txtEMAIL.getText());
            objNewCustomer.setJobTitle(txtJOB.getText());

            //Call add method to do the work
            success = objemployeeList.add(objNewCustomer.getSSNumber(), objNewCustomer);

            //Process results
            if (success) {

                JOptionPane.showMessageDialog(null,"Employee Added");
            } else {

                JOptionPane.showMessageDialog(null,"No available space!");
            }
        }
        catch (Exception objE) {
            //Trapping for any errors 
            JOptionPane.showMessageDialog(null, objE.toString());        
        }  
    }//GEN-LAST:event_addBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
          try {        

            //Create temporary variables
            boolean success;

  

            //Call Edit method to do the work
            success = objemployeeList.edit(txtSS.getText(), txtFN.getText(), txtLN.getText(), txtDOB.getText(),
                    txtADDRESS.getText(), txtPHONE.getText(),txtAGE.getText(),txtJOB.getText());

            //Process results
            if (success) {

                JOptionPane.showMessageDialog(null,"Employee record modified");
            } else {

                JOptionPane.showMessageDialog(null,"Employee not found!");
            }
        }
        catch (Exception objE) {
            //Trapping for any errors 
            JOptionPane.showMessageDialog(null, objE.toString());                
        }  
    }//GEN-LAST:event_editBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
        try {

            //Create temporary variables
            boolean success;

 
            //Call Remove method to delete customer from list
            success = objemployeeList.remove(txtSS.getText());

            //Process results
            if (success) {
 
                JOptionPane.showMessageDialog(null,"Employee deleted");
            } else {

                JOptionPane.showMessageDialog(null,"Employee not found!");
            }
        }
        catch (Exception objE) {
            //Trapping for any errors 
                JOptionPane.showMessageDialog(null,objE.toString());           
        }  
    }//GEN-LAST:event_removeBtnActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        // TODO add your handling code here:
        try {       

            //Create temporary variables
            boolean success;


            //Call Print method to print customer
            success = objemployeeList.print(txtSS.getText());

            //Process results
            if (!success) {

                JOptionPane.showMessageDialog(null,"Employee not found!");
            }
        }
        catch (Exception objE) {
            //Trapping for any errors 
                JOptionPane.showMessageDialog(null,objE.toString());           
        }  
    }//GEN-LAST:event_printBtnActionPerformed

    private void printallBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printallBtnActionPerformed
        // TODO add your handling code here:
           try {            
 
            //Call PrintAllCustomer() method to print all the customer
            objemployeeList.printAll();

            }
            catch (Exception objE) {
                //Trapping for any errors 
                JOptionPane.showMessageDialog(null,objE.toString());       
        }  
    }//GEN-LAST:event_printallBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtSS.setText(null);
        txtFN.setText(null);
        txtLN.setText(null);
        txtAGE.setText(null);
        txtADDRESS.setText(null);
        txtDOB.setText(null);
        txtPHONE.setText(null);
        txtEMAIL.setText(null);
        txtJOB.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagemenetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagemenetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagemenetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagemenetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeManagemenetForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList EmployeeList1;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel addLbl;
    private javax.swing.JLabel ageLbl;
    private javax.swing.JLabel dobLbl;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel fnLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jobLbl;
    private javax.swing.JButton listBtn;
    private javax.swing.JLabel lnLbl;
    private javax.swing.JLabel phLbl;
    private javax.swing.JButton printBtn;
    private javax.swing.JButton printallBtn;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel ssLbl;
    private javax.swing.JTextField txtADDRESS;
    private javax.swing.JTextField txtAGE;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEMAIL;
    private javax.swing.JTextField txtFN;
    private javax.swing.JTextField txtJOB;
    private javax.swing.JTextField txtLN;
    private javax.swing.JTextField txtPHONE;
    private javax.swing.JTextField txtSS;
    // End of variables declaration//GEN-END:variables
}
