/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIclient;

/**
 *
 * @author Fahmee
 */
import java.awt.Color;
import javax.swing.JOptionPane;
public class PointOfSaleFrame extends javax.swing.JFrame {

    /**
     * Creates new form PointOfSaleFrame
     */
    public PointOfSaleFrame() {
        initComponents();
        this.getContentPane().setBackground(Color.blue);
         setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        posLbl = new javax.swing.JLabel();
        carrentalBtn = new javax.swing.JButton();
        carreturnBtn = new javax.swing.JButton();
        cusmanBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        posLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        posLbl.setText("POINT-OF-SALES");

        carrentalBtn.setText("Car Rental");
        carrentalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrentalBtnActionPerformed(evt);
            }
        });

        carreturnBtn.setText("Car Return");
        carreturnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carreturnBtnActionPerformed(evt);
            }
        });

        cusmanBtn.setText("Customer Management");
        cusmanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusmanBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("EXIT");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(posLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitBtn)
                    .addComponent(cusmanBtn)
                    .addComponent(carreturnBtn)
                    .addComponent(carrentalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {carrentalBtn, carreturnBtn, cusmanBtn, exitBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(posLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(carrentalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(carreturnBtn)
                .addGap(43, 43, 43)
                .addComponent(cusmanBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(exitBtn)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {carrentalBtn, carreturnBtn, cusmanBtn, exitBtn});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void carrentalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrentalBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Car rental Operation is Under Construction");
        
    }//GEN-LAST:event_carrentalBtnActionPerformed

    private void carreturnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carreturnBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Car rental Operation is Under Construction");
    }//GEN-LAST:event_carreturnBtnActionPerformed

    private void cusmanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusmanBtnActionPerformed
        // TODO add your handling code here:
        CustomerManagementPortal objCMForm = new CustomerManagementPortal();
        objCMForm.setVisible(true);
        objCMForm.setLocationRelativeTo(null);
    }//GEN-LAST:event_cusmanBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PointOfSaleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PointOfSaleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PointOfSaleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PointOfSaleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PointOfSaleFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton carrentalBtn;
    private javax.swing.JButton carreturnBtn;
    private javax.swing.JButton cusmanBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel posLbl;
    // End of variables declaration//GEN-END:variables
}
